name: adapters
description: Infrastructure adapters providing concrete implementations for connectivity, DI, HTTP, logging, routing, storage, time services, and network queue management.
publish_to: none
version: 0.4.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bootstrap: 
    git: 
      url: https://github.com/Enri-code/flutter-bootstrap 
      ref: v0.5.3